name = "Create- Aired out"
author = "nicc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6baba6bc1f0bdad1c049cca13f11ad6f4156540f3443d258da54e382620a819"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
