name = "Create- Aired out"
author = "nicc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "880182e17935b25e1000fb1a10df57ebef36f91824be1e25750a5c3d3301b16a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
